//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Product_Category_Mapping = new HashSet<Product_Category_Mapping>();
        }
    
        public int Id { get; set; }
        public string CateName { get; set; }
        public string ShortUrl { get; set; }
        public string Icon { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public Nullable<int> ModuleId { get; set; }
    
        public virtual ICollection<Product_Category_Mapping> Product_Category_Mapping { get; set; }
    }
}
