//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FooterMenu
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<long> ArticleId { get; set; }
        public string Target { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
