//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Product_Category_Mapping = new HashSet<Product_Category_Mapping>();
        }
    
        public long Id { get; set; }
        public string ProductName { get; set; }
        public string Descriptions { get; set; }
        public string ShortDesc { get; set; }
        public string ShortUrl { get; set; }
        public string ImageDefault { get; set; }
        public string Images { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDesc { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsPromote { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
    
        public virtual ICollection<Product_Category_Mapping> Product_Category_Mapping { get; set; }
    }
}
